# Generated by Django 2.1 on 2019-12-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_limit', models.FloatField(max_length=10, verbose_name='上限值')),
                ('l_limit', models.FloatField(max_length=10, verbose_name='下限值')),
                ('t_value', models.FloatField(max_length=10, verbose_name='目标值')),
                ('status', models.CharField(choices=[('disabled', '禁用'), ('unused', '未使用'), ('using', '使用中')], default='unused', max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '部门KPI',
                'verbose_name_plural': '部门KPI',
                'ordering': ['id', 'dep'],
                'permissions': (('add_groupkpi', '添加部门KPI'), ('change_groupkpi', '修改部门KPI'), ('delete_groupkpi', '删除部门KPI'), ('view_groupkpi', '查看部门KPI')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('unit', models.CharField(max_length=32, verbose_name='单位')),
                ('in_time', models.CharField(max_length=32, verbose_name='录入时间')),
                ('mo_time', models.CharField(max_length=32, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('disabled', '禁用'), ('unused', '未使用'), ('using', '使用中')], default='unused', max_length=32, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPI',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KpiInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_value', models.FloatField(max_length=10, verbose_name='实际值')),
                ('month', models.DateField(verbose_name='月份')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('group_kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_group', to='kpi.GroupKPI', verbose_name='部门KPI')),
            ],
            options={
                'verbose_name': 'KPI数据输入',
                'verbose_name_plural': 'KPI数据输入',
                'ordering': ['month'],
                'permissions': (('add_kpiinput', '添加数据'), ('change_kpiinput', '修改数据'), ('delete_kpiinput', '删除数据'), ('view_kpiinput', '查看数据')),
                'default_permissions': (),
            },
        ),
    ]
