# Generated by Django 2.1 on 2019-12-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupkpi',
            name='status',
            field=models.CharField(choices=[('unused', '未使用'), ('using', '使用中'), ('disabled', '禁用')], default='unused', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='status',
            field=models.CharField(choices=[('unused', '未使用'), ('using', '使用中'), ('disabled', '禁用')], default='unused', max_length=32, verbose_name='状态'),
        ),
    ]
