# Generated by Django 2.2.1 on 2019-12-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_auto_20191211_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupkpi',
            name='status',
            field=models.CharField(choices=[('using', '使用中'), ('disabled', '禁用'), ('unused', '未使用')], default='unused', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='status',
            field=models.CharField(choices=[('using', '使用中'), ('disabled', '禁用'), ('unused', '未使用')], default='unused', max_length=32, verbose_name='状态'),
        ),
    ]
