# Generated by Django 2.2.1 on 2019-11-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='creator',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='用户名'),
        ),
    ]
