# Generated by Django 2.2.1 on 2019-11-30 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': (), 'permissions': (('add_departments', '添加部门'), ('change_departments', '修改部门'), ('delete_departments', '删除部门'), ('view_departments', '查看部门')), 'verbose_name': '组织架构', 'verbose_name_plural': '组织架构'},
        ),
    ]
