# Generated by Django 2.2.1 on 2019-11-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20191130_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'default_permissions': (), 'permissions': (('add_organization', '添加部门'), ('change_organization', '修改部门'), ('delete_organization', '删除部门'), ('view_organization', '查看部门')), 'verbose_name': '组织架构', 'verbose_name_plural': '组织架构'},
        ),
    ]
